export enum SwapStatus {
  ORDER_PLACED = "ORDER_PLACED",
  HTLC_EVM_CREATE = "HTLC_EVM_CREATE",
  HTLC_APTOS_CREATE = "HTLC_APTOS_CREATE",
  HTLC_EVM_COMPLETED = "HTLC_EVM_COMPLETED",
  HTLC_APTOS_COMPLETED = "HTLC_APTOS_COMPLETED",
  HTLC_EVM_REFUNDED = "HTLC_EVM_REFUNDED",
  HTLC_APTOS_REFUNDED = "HTLC_APTOS_REFUNDED",
  WITHDRAW_EVM_ASSETS = "WITHDRAW_EVM_ASSETS",
  WITHDRAW_APTOS_ASSETS = "WITHDRAW_APTOS_ASSETS",
  CANCELLED = "CANCELLED",
}
