services:
  swap-db:
    image: postgres:15
    container_name: swap-db
    ports:
      - "5483:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: swap_db
    volumes:
      - postgres-data:/var/lib/postgresql/data 
volumes:
  postgres-data: